extends:
  - eslint:recommended
  - prettier
  - plugin:react/recommended
parser: babel-eslint
plugins:
  - react
  - prettier
parserOptions:
  ecmaVersion: 9
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
rules:
  react/prop-types: off
  prettier/prettier: error
env:
  browser: true
globals:
  __DEV_LOGSTORE: true
